apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name: etax # your application name
  name: etax
spec:
  output:
    to:
      kind: DockerImage
      name: docker.io/delenies/etax:latest
  source:
    type: Git
    git:
      uri: https://github.com/missprempree/etax-api
      ref: master
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in ./Dockerfile
      dockerfilePath: DockerFile
