apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: etax
spec:
  source:
    type: Git
    git:
      uri: https://github.com/missprempree/etax-api.git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: DockerFile  # Ensure this path is correct
  output:
    to:
      kind: DockerImage
      name: docker.io/delenies/etax:latest
  resources: {}
  postCommit: {}
  nodeSelector: null
  triggers:
    - type: ConfigChange
