apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: etax-api
spec:
  output:
    to:
      kind: DockerImage
      name: 'docker.pkg.github.com/missprempree/etax-api/etax-api-img:latest'
    pushSecret:
      name: etax-frontend-pull-secret
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in ./Dockerfile
      dockerfilePath: Dockerfile
