# Build the application first using Maven
FROM maven:4-openjdk-17 as build
WORKDIR /app
COPY . .
RUN mvn install

# Inject the JAR file into a new container to keep the file small
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/target/etax-*.jar /app/app.jar
EXPOSE 9005
ENTRYPOINT ["sh", "-c"]
CMD ["java -jar app.jar"]
